batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- QObs(mm/d)
data_dir: ../../../../../gladwell/hydrology/SUMMA/summa-ml-models/CAMELS_US
dataset: camels_us
device: cuda:1
dynamic_inputs:
- prcp(mm/day)
- tmin(C)
- tmax(C)
- srad(W/m2)
- vp(Pa)
epochs: 50
experiment_name: 04185000_lstm
forcings: daymet
head: regression
hidden_size:
- 64
initial_forget_bias: 3
learning_rate:
  0: 1e-2
  30: 5e-3
  40: 1e-3
log_interval: 50
log_n_figures: 1
log_tensorboard: true
loss: NSE
metrics:
- NSE
- Alpha-NSE
- Beta-NSE
- FHV
- FMS
- FLV
- KGE
- Beta-KGE
- Peak-Timing
- Peak-MAPE
- Pearson-r
model: cudalstm
num_workers: 8
optimizer: Adam
output_activation: linear
output_dropout: 0.4
predict_last_n: 1
run_folder_name: runs_569_basins_lstm_single_random-seed
save_weights_every: 50
seq_length: 365
target_variables:
- QObs(mm/d)
test_basin_file: 04185000_file.txt
test_end_date: 30/09/2010
test_start_date: 01/10/2000
train_basin_file: 04185000_file.txt
train_end_date: 30/09/2000
train_start_date: 01/10/1980
validate_every: 50
validate_n_random_basins: 1
validation_basin_file: 04185000_file.txt
validation_end_date: 30/09/2010
validation_start_date: 01/10/2000
