batch_size: 128
clip_gradient_norm: 1
clip_targets_to_zero:
- q_obs
data_dir: ../../../../../gladwell/hydrology/SUMMA/summa-ml-models/CAMELS_spat_NH
dataset: camels_spat
device: cuda:0
dynamic_inputs:
- e
- mper
- msdwlwrf
- msdwswrf
- msnlwrf
- msnswrf
- mtpr
- q
- rh
- sp
- t
- u
- v
- w
- phi
- tmean
- prcp
epochs: 30
<<<<<<< HEAD
experiment_name: 416_b2c_4444
=======
experiment_name: 416_b2c
>>>>>>> bbf0e66... Change experiment name in ensemble script
forcings: null
head: regression
hidden_size:
- 128
initial_forget_bias: 3
learning_rate: 1e-4
log_interval: 5
log_n_figures: 2
log_tensorboard: true
loss: NSE
metrics:
- NSE
- Alpha-NSE
- Beta-NSE
- FHV
- FMS
- FLV
- KGE
- Beta-KGE
- Peak-Timing
- Peak-MAPE
- Pearson-r
model: cudalstm
num_workers: 16
optimizer: Adam
output_activation: linear
output_dropout: 0.6
predict_last_n: 1
<<<<<<< HEAD
save_weights_every: 2
seed: 4444
=======
save_weights_every: 5
seed: 5555
>>>>>>> bbf0e66... Change experiment name in ensemble script
seq_length: 365
target_variables:
- q_obs
test_basin_file: 416_basin_camels_spat_1975-2019_usa_best.txt
test_end_date: 30/09/2019
test_start_date: 01/10/2007
train_basin_file: 416_basin_camels_spat_1975-2019_usa_best.txt
train_end_date: 30/09/1995
train_start_date: 01/10/1975
validate_every: 5
validate_n_random_basins: 5
validation_basin_file: 416_basin_camels_spat_1975-2019_usa_best.txt
validation_end_date: 30/09/2007
validation_start_date: 01/10/1995
