batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- q_obs
data_dir: ../../../../../gladwell/hydrology/SUMMA/summa-ml-models/CAMELS_spat_NH
dataset: camels_spat
device: cuda:0
dynamic_inputs:
- e
- mper
- msdwlwrf
- msdwswrf
- msnlwrf
- msnswrf
- mtpr
- q
- rh
- sp
- t
- u
- v
- w
- phi
- tmean
- prcp
epochs: 30
experiment_name: 512_nh_paper_camelsspat_ealstm19static17inp_444
forcings: null
head: regression
hidden_size:
- 256
initial_forget_bias: 5
learning_rate:
  0: 1e-3
  11: 5e-4
  21: 1e-5
log_interval: 5
log_n_figures: 2
log_tensorboard: true
loss: NSE
metrics:
- NSE
- Alpha-NSE
- Beta-NSE
- FHV
- FMS
- FLV
- KGE
- Beta-KGE
- Peak-Timing
- Peak-MAPE
- Pearson-r
model: ealstm
num_workers: 16
optimizer: Adam
output_activation: linear
output_dropout: 0.4
predict_last_n: 1
save_weights_every: 5
seed: 444
seq_length: 270
static_attributes:
- aridity1_mean
- fracsnow1_mean
- seasonality1_mean
- low_prec_dur_mean
- high_prec_freq
- high_prec_dur_mean
- prec_mean
- pet_mean
- basin_area
- elev_mean
- slope_mean
- soil_thickness_mean
- porosity_mean
- log_permeability_mean
- lai_mean_month_max
- lai_mean_month_diff
- sand_layer_mean
- silt_layer_mean
- clay_layer_mean
target_variables:
- q_obs
test_basin_file: 512_basin_camels_spat_1989-2008_usa.txt
test_end_date: 30/09/1999
test_start_date: 01/10/1989
train_basin_file: 512_basin_camels_spat_1989-2008_usa.txt
train_end_date: 30/09/2008
train_start_date: 01/10/1999
validate_every: 50
validate_n_random_basins: 5
validation_basin_file: 512_basin_camels_spat_1989-2008_usa.txt
validation_end_date: 30/09/1999
validation_start_date: 01/10/1989
