batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- QObs(mm/d)
data_dir: ../../../../../gladwell/hydrology/SUMMA/summa-ml-models/CAMELS_US
dataset: camels_us
device: cuda:1
dynamic_inputs:
- prcp(mm/day)
- tmin(C)
- tmax(C)
- srad(W/m2)
- vp(Pa)
epochs: 30
experiment_name: 569_cluster2of17_20f_ealstm_888
forcings: daymet
head: regression
hidden_size:
- 256
initial_forget_bias: 5
learning_rate:
  0: 1e-3
  11: 5e-4
  21: 1e-5
log_interval: 5
log_n_figures: 2
log_tensorboard: true
loss: NSE
metrics:
- NSE
- Alpha-NSE
- Beta-NSE
- FHV
- FMS
- FLV
- KGE
- Beta-KGE
- Peak-Timing
- Peak-MAPE
- Pearson-r
model: ealstm
num_workers: 16
optimizer: Adam
output_activation: linear
output_dropout: 0.4
predict_last_n: 1
save_weights_every: 5
seed: 888
seq_length: 270
static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
- p_seasonality
target_variables:
- QObs(mm/d)
test_basin_file: 569_basins_17clusters/569_basin_file_cluster2of17_46_20first.txt
test_end_date: 30/09/2010
test_start_date: 01/10/2000
train_basin_file: 569_basins_17clusters/569_basin_file_cluster2of17_46_20first.txt
train_end_date: 30/09/2000
train_start_date: 01/10/1980
validate_every: 5
validate_n_random_basins: 5
validation_basin_file: 569_basins_17clusters/569_basin_file_cluster2of17_46_20first.txt
validation_end_date: 30/09/2010
validation_start_date: 01/10/2000
