batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- q_obs
data_dir: ../../../../../gladwell/hydrology/SUMMA/summa-ml-models/CAMELS_spat_NH
dataset: camels_spat
device: cuda:1
dynamic_inputs:
- e
- mper
- msdwlwrf
- msdwswrf
- msnlwrf
- msnswrf
- mtpr
- q
- rh
- sp
- t
- u
- v
- w
- phi
- tmean
- prcp
epochs: 30
experiment_name: 928_cyril_camelsspat_666
forcings: null
head: regression
hidden_size:
- 256
initial_forget_bias: 5
learning_rate:
  0: 1e-3
  11: 5e-4
  21: 1e-5
log_interval: 5
log_n_figures: 2
log_tensorboard: true
loss: NSE
metrics:
- NSE
- Alpha-NSE
- Beta-NSE
- FHV
- FMS
- FLV
- KGE
- Beta-KGE
- Peak-Timing
- Peak-MAPE
- Pearson-r
model: cudalstm
num_workers: 16
optimizer: Adam
output_activation: linear
output_dropout: 0.4
predict_last_n: 1
save_weights_every: 5
seed: 666
seq_length: 270
target_variables:
- q_obs
test_basin_file: 928_cyril_basins_can_usa.txt
test_end_date: 30/09/1999
test_start_date: 01/10/1989
train_basin_file: 928_cyril_basins_can_usa.txt
train_end_date: 30/09/2008
train_start_date: 01/10/1999
validate_every: 50
validate_n_random_basins: 5
validation_basin_file: 928_cyril_basins_can_usa.txt
validation_end_date: 30/09/1999
validation_start_date: 01/10/1989
