batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- q_obs
data_dir: ../../../DATA/CAMELS_spat_NH
dataset: camels_spat
device: cuda:0
dynamic_inputs:
- e
- mper
- msdwlwrf
- msdwswrf
- msnlwrf
- msnswrf
- mtpr
- q
- rh
- sp
- t
- u
- v
- w
- phi
- tmean
- prcp
epochs: 2
experiment_name: 10_camels_spat_USA
head: regression
hidden_size: 64
initial_forget_bias: 3
learning_rate: 1e-3
log_interval: 2
log_n_figures: 2
log_tensorboard: true
loss: MSE
metrics:
- NSE
- Alpha-NSE
- Beta-NSE
- FHV
- FMS
- FLV
- KGE
- Beta-KGE
- Peak-Timing
- Peak-MAPE
- Pearson-r
model: cudalstm
num_workers: 16
optimizer: Adam
output_activation: linear
<<<<<<< HEAD
output_dropout: 0.4
=======
output_dropout: 0.0
>>>>>>> 5b313ea... Added discharge normalization by area and updated the tining scripts
predict_last_n: 1
save_weights_every: 1
seed: 1111
seq_length: 270
target_variables:
- q_obs
test_basin_file: 10_basin_camels_spat.txt
test_end_date: 30/09/2019
test_start_date: 01/10/2010
train_basin_file: 10_basin_camels_spat.txt
train_end_date: 30/09/2005
train_start_date: 01/10/1980
validate_every: 5
validate_n_random_basins: 5
validation_basin_file: 10_basin_camels_spat.txt
validation_end_date: 30/09/2010
validation_start_date: 01/10/2005
