# Files directory
data_dir: ../../../../../../gladwell/hydrology/SUMMA/summa-ml-models

map_shape_file: CAMELS_US/basin_set_full_res/usa-states-census-2014.shp
hm_catchment: CAMELS_US/basin_set_full_res/HCDN_nhru_final_671.shp

metrics4plotting: 
  - NSE 
  - KGE
metrics4table:
  - NSE
  - Alpha-NSE
  - Beta-NSE
  - FHV
  - FMS
  - FLV

# result_dir: runs_531_nh_paper
# result_dir: runs_505_nh_paper_camelsspat
# result_dir: runs_505_nh_paper_camelsspat_17inp
# result_dir: runs_505_nh_paper_camelsspat_emearth
# result_dir: runs_531_nh_paper_ealstm
# result_dir: runs_505_nh_paper_camelsspat_14inp
# result_dir: runs_505_nh_paper_camelsspat_ealstm19static
# result_dir: runs_505_nh_paper_camelsspat_ealstm19static17inp
# result_dir: runs_512_nh_paper_camelsspat_ealstm19static17inp
# result_dir: runs_505_nh_paper_camelsspat_ealstm24static17inp
# result_dir: runs_505_nh_paper_camelsspat_ealstm24static40inp_extraMinMaxT
# result_dir: runs_505_nh_paper_camelsspat_ealstm24static36inp_noExtra
# result_dir: runs_505_nh_paper_camelsspat_ealstm24static34inp_noExtra_noEmEarth
# result_dir: runs_569_cluster2of17_20f_ealstm
# result_dir: runs_569_basins_camels_ealstm
# result_dir: runs_569_basins_lstm_single_random-seed
# result_dir: runs_569_basins_lstm_single_111
result_dir: runs_569_basins_lstm_single_ensemble_8seeds
# result_dir: M100_results_569basins_1980_2010_BS3_julia_150ep_lr4

result_file: 
  # test_ensemble_metrics.csv
  # test_metrics_seed111.csv
  # test_all-single_random-seed.csv
  # test_all-single_111.csv
  test_all-single_ensemble_8seeds.csv
  # metrics_test.csv
files4table:
  - 111.csv
  - 222.csv
  - 333.csv
  - 444.csv
  - 555.csv
  - 666.csv
  - 777.csv
  - 888.csv
  - test_ensemble_metrics.csv

folders4cdf_dir:
  - directory: runs_531_nh_paper
    experiment: 'E0a (LSTM: 5)$^*$'
    color: 'tab:red'
    marker: o
    linestyle: '-.'
    colname: 'camels_5dyn'
  - directory: runs_505_nh_paper_camelsspat_emearth
    experiment: 'E0b (LSTM: 5)$^\dagger$'
    color: 'tab:purple'
    marker: null
    linestyle: '-.'
    colname: 'camels_spat_5dyn'
  - directory: runs_505_nh_paper_camelsspat_17inp
    experiment: 'E0c (LSTM: 17)$^\dagger$'
    color: 'tab:orange'
    marker: null 
    linestyle: '-.'
    colname: 'camels_spat_17dyn'
  - directory: runs_531_nh_paper_ealstm
    experiment: 'E1a (EA-LSTM: 5+27)$^*$'
    color: 'tab:blue'
    marker: o
    linestyle: '--'
    colname: 'camels_5dyn_27stat'
  - directory: runs_505_nh_paper_camelsspat_ealstm19static
    experiment: 'E1b (EA-LSTM: 5+19)$^\dagger$'
    color: 'tab:green'
    marker: null 
    linestyle: '--'
    colname: 'camels_spat_5dyn_19stat'
  - directory: runs_505_nh_paper_camelsspat_ealstm19static17inp
    experiment: 'E1c (EA-LSTM: 17+19)$^\dagger$'
    color: 'tab:cyan'
    marker: null 
    linestyle: '--'
    colname: 'camels_spat_17dyn_19stat'
  - directory: runs_505_nh_paper_camelsspat_ealstm24static17inp
    experiment: 'E1d (EA-LSTM: 17+24)$^{\dagger}$'
    color: 'tab:gray'
    marker: null
    linestyle: '--'
    colname: 'camels_spat_17dyn_24stat'
  - directory: runs_505_nh_paper_camelsspat_ealstm24static40inp_extraMinMaxT
    experiment: 'E1e (EA-LSTM: 40+24)$^{\dagger}$'
    color: 'k'
    marker: null
    linestyle: '--'
    colname: 'camels_spat_40dyn_24stat'
  - directory: runs_505_nh_paper_camelsspat_ealstm24static36inp_noExtra
    experiment: 'E1f (EA-LSTM: 36+24 - no extra)$^{\dagger}$'
    color: 'tab:brown'
    marker: null
    linestyle: '--'
    colname: 'camels_spat_36dyn_24stat'
  - directory: runs_505_nh_paper_camelsspat_ealstm24static36inp_extra_noEmEarth
    experiment: 'E1g (EA-LSTM: 36+24 - no em-earth)$^{\dagger}$'
    color: 'tab:olive'
    marker: null
    linestyle: '--'
    colname: 'camels_spat_36dyn_24stat_noEmEarth'
  - directory: runs_505_nh_paper_camelsspat_ealstm24static34inp_noExtra_noEmEarth
    experiment: 'E1h (EA-LSTM: 34+24 - no extra, no em-earth)$^{\dagger}$'
    color: 'tab:purple'
    marker: null
    linestyle: '--'
    colname: 'camels_spat_34dyn_24stat_noExtra_noEmEarth'




  # # # - directory: runs_512_nh_paper_camelsspat_ealstm19static17inp
  # # #   experiment: 'E1d (LSTM: 17+19)$^{\dagger\dagger}$'
  # # #   color: 'blue'
  # # #   marker: null 
  # # #   linestyle: '--'
  # - directory: runs_928_cyril_camelsspat
  #   experiment: 'E2a (LSTM: 17)$^\diamond$'
  #   color: 'tab:olive'
  #   marker: o
  #   linestyle: '-'
  # # - directory: runs_928_cyril_camelsspat_ealstm19static
  # #   experiment: 'E2b (EA-LSTM: 17+19)$^\star$'
  # #   color: 'tab:brown'
  # #   marker: null 
  # #   linestyle: '--'
  # - directory: runs_915_cyril_camelsspat_ealstm24static
  #   experiment: 'E2c (EA-LSTM: 17+24)$^{\diamond\diamond}$'
  #   color: 'olive'
  #   marker: null 
  #   linestyle: '--'



# # result_dir: runs_531_nh_paper_1900
# result_dir: runs_b2c_416_ensemble_long_17inp
# result_file: 
#   test_ensemble_metrics.csv
# files4table:
#   - 1111.csv
#   - 2222.csv
#   - 3333.csv
#   - 4444.csv
#   - 5555.csv
#   - 6666.csv
#   - 7777.csv
#   - 8888.csv
#   - test_ensemble_metrics.csv














# ## NH run on 531 CAMELS catchments with EA-LSTM/LSTM model
# result_dir: 531_camels_ealstm
# result_file: 
#   # test_metrics_531camels_ealstm_seed111.csv
#   # test_metrics_531camels_ealstm_seed111flv07.csv
#   test_metrics_531camels_ealstm_seed111flv07valid.csv
#   # test_metrics_531camels_lstm_seed111.csv
# files4table:
#   - test_metrics_531camels_ealstm_seed111.csv
#   - test_metrics_531camels_ealstm_seed111flv07.csv
#   - test_metrics_531camels_ealstm_seed111flv07valid.csv
#   # - test_metrics_531camels_lstm_seed111.csv
#   # - test_metrics_531camels_lstm_seed111flv07.csv


# ## NH run on 426 CAMELS_spat catchments
# result_dir: 426_camels_spat_usa
# result_file: 
#   test_metrics_cedar_batch1b_15inp.csv
#   # test_metrics_cedar_batch3a.csv
#   # test_metrics_cedar_batch1b.csv
#   # test_metrics_cedar_batch1a.csv
#   # test_metrics_norm-area_v0.csv
#   # test_metrics_norm-area_v1.csv
# files4table:
#   - test_metrics_cedar_batch1b_15inp.csv
#   - test_metrics_cedar_batch3a.csv
#   - test_metrics_cedar_batch1b.csv
#   - test_metrics_cedar_batch1a.csv
#   - test_metrics_norm-area_v0.csv
#   - test_metrics_norm-area_v1.csv


# ## NH run on 416 CAMELS_spat catchments
# result_dir: 416_camels_spat_usa
# result_file: 
#   test_metrics_17inp.csv
# files4table:
#   - test_metrics_17inp.csv


# ## NH run on 416 CAMELS_spat catchments
# result_dir: 416_camels_spat_usa
# result_file: 
#   test_metrics_cedar_batch2c.csv
# files4table:
#   - test_metrics_cedar_batch2c.csv


# result_dir: EALSTM_PAPER_results_loss_NSE
# result_file: 
#   # test_metrics_531camels_ealstm_seed111.csv
#   test_metrics_531camels_ealstm_ensemble.csv
# files4table:
#   - test_metrics_531camels_ealstm_seed111.csv
#   - test_metrics_531camels_ealstm_seed222.csv
#   - test_metrics_531camels_ealstm_seed333.csv
#   - test_metrics_531camels_ealstm_seed444.csv
#   - test_metrics_531camels_ealstm_seed555.csv
#   - test_metrics_531camels_ealstm_seed666.csv
#   - test_metrics_531camels_ealstm_seed777.csv
#   - test_metrics_531camels_ealstm_seed888.csv
#   - test_metrics_531camels_ealstm_ensemble.csv

#   - test_metrics_531camels_lstm_seed111.csv
#   - test_metrics_531camels_lstm_seed222.csv
#   - test_metrics_531camels_lstm_seed333.csv
#   - test_metrics_531camels_lstm_seed444.csv
#   - test_metrics_531camels_lstm_seed555.csv
#   - test_metrics_531camels_lstm_seed666.csv
#   - test_metrics_531camels_lstm_seed777.csv
#   - test_metrics_531camels_lstm_seed888.csv
#   - test_metrics_531camels_lstm_ensemble.csv

# result_dir: 426_camels_spat_usa
# result_dir: 447_camels_ealstm
# result_dir: 531_camels_ealstm
# result_dir: EALSTM_PAPER_results_loss_MSE
# result_dir: EALSTM_PAPER_results_loss_NSE

# result_file:
#   # test_metrics_531camels_ealstm.csv
#   # test_metrics_531camels_lstm.csv
#   # test_metrics_447camels_ealstm.csv
#   # test_metrics_447camels_lstm.csv
#   test_metrics_531camels_ealstm_seed111.csv
#   # test_metrics_531camels_lstm_seed111.csv


# files4table:
#   # - test_metrics_447camels_ealstm.csv
#   # - test_metrics_447camels_lstm.csv
#   - test_metrics_531camels_ealstm_seed111.csv
#   - test_metrics_531camels_lstm_seed111.csv

# metrics4table:
# # NSE,Alpha-NSE,Beta-NSE,FHV,FMS,FLV
#   - NSE
#   - Alpha-NSE
#   - Beta-NSE
#   - FHV
#   - FMS
#   - FLV


